from .usuario_model import Usuario
from .passageiro_model import Passageiro
from .motorista_model import Motorista
from .tipo_combustivel_model import TipoCombustivel
from .modelo_veiculo_model import ModeloVeiculo
from .classe_veiculo_model import ClasseVeiculo
from .veiculo_model import Veiculo
from .motorista_veiculo_model import MotoristaVeiculo
from .metodo_pagamento_model import MetodoPagamento
from .avaliacao_model import Avaliacao
from .servico_model import Servico
from .corrida_model import Corrida
from .pagamento_model import Pagamento